// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queryinput.proto

package com.samdasu.netty.protocol;

public final class QueryInputProtos {
  private QueryInputProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QueryInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.QueryInput.text query_input = 1;</code>
     * @return Whether the queryInput field is set.
     */
    boolean hasQueryInput();
    /**
     * <code>.QueryInput.text query_input = 1;</code>
     * @return The queryInput.
     */
    com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text getQueryInput();
    /**
     * <code>.QueryInput.text query_input = 1;</code>
     */
    com.samdasu.netty.protocol.QueryInputProtos.QueryInput.textOrBuilder getQueryInputOrBuilder();
  }
  /**
   * Protobuf type {@code QueryInput}
   */
  public  static final class QueryInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QueryInput)
      QueryInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryInput.newBuilder() to construct.
    private QueryInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryInput() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryInput();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.Builder subBuilder = null;
              if (queryInput_ != null) {
                subBuilder = queryInput_.toBuilder();
              }
              queryInput_ = input.readMessage(com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(queryInput_);
                queryInput_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.samdasu.netty.protocol.QueryInputProtos.internal_static_QueryInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.samdasu.netty.protocol.QueryInputProtos.internal_static_QueryInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.samdasu.netty.protocol.QueryInputProtos.QueryInput.class, com.samdasu.netty.protocol.QueryInputProtos.QueryInput.Builder.class);
    }

    public interface textOrBuilder extends
        // @@protoc_insertion_point(interface_extends:QueryInput.text)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string text = 1;</code>
       * @return The text.
       */
      java.lang.String getText();
      /**
       * <code>string text = 1;</code>
       * @return The bytes for text.
       */
      com.google.protobuf.ByteString
          getTextBytes();

      /**
       * <code>string language_code = 2;</code>
       * @return The languageCode.
       */
      java.lang.String getLanguageCode();
      /**
       * <code>string language_code = 2;</code>
       * @return The bytes for languageCode.
       */
      com.google.protobuf.ByteString
          getLanguageCodeBytes();
    }
    /**
     * Protobuf type {@code QueryInput.text}
     */
    public  static final class text extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:QueryInput.text)
        textOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use text.newBuilder() to construct.
      private text(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private text() {
        text_ = "";
        languageCode_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new text();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private text(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                text_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                languageCode_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.samdasu.netty.protocol.QueryInputProtos.internal_static_QueryInput_text_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.samdasu.netty.protocol.QueryInputProtos.internal_static_QueryInput_text_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.class, com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.Builder.class);
      }

      public static final int TEXT_FIELD_NUMBER = 1;
      private volatile java.lang.Object text_;
      /**
       * <code>string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int LANGUAGE_CODE_FIELD_NUMBER = 2;
      private volatile java.lang.Object languageCode_;
      /**
       * <code>string language_code = 2;</code>
       * @return The languageCode.
       */
      public java.lang.String getLanguageCode() {
        java.lang.Object ref = languageCode_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          languageCode_ = s;
          return s;
        }
      }
      /**
       * <code>string language_code = 2;</code>
       * @return The bytes for languageCode.
       */
      public com.google.protobuf.ByteString
          getLanguageCodeBytes() {
        java.lang.Object ref = languageCode_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          languageCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getTextBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
        }
        if (!getLanguageCodeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, languageCode_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getTextBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
        }
        if (!getLanguageCodeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, languageCode_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text)) {
          return super.equals(obj);
        }
        com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text other = (com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text) obj;

        if (!getText()
            .equals(other.getText())) return false;
        if (!getLanguageCode()
            .equals(other.getLanguageCode())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
        hash = (37 * hash) + LANGUAGE_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getLanguageCode().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code QueryInput.text}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:QueryInput.text)
          com.samdasu.netty.protocol.QueryInputProtos.QueryInput.textOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.samdasu.netty.protocol.QueryInputProtos.internal_static_QueryInput_text_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.samdasu.netty.protocol.QueryInputProtos.internal_static_QueryInput_text_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.class, com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.Builder.class);
        }

        // Construct using com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          text_ = "";

          languageCode_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.samdasu.netty.protocol.QueryInputProtos.internal_static_QueryInput_text_descriptor;
        }

        @java.lang.Override
        public com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text getDefaultInstanceForType() {
          return com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.getDefaultInstance();
        }

        @java.lang.Override
        public com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text build() {
          com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text buildPartial() {
          com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text result = new com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text(this);
          result.text_ = text_;
          result.languageCode_ = languageCode_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text) {
            return mergeFrom((com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text other) {
          if (other == com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.getDefaultInstance()) return this;
          if (!other.getText().isEmpty()) {
            text_ = other.text_;
            onChanged();
          }
          if (!other.getLanguageCode().isEmpty()) {
            languageCode_ = other.languageCode_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object text_ = "";
        /**
         * <code>string text = 1;</code>
         * @return The text.
         */
        public java.lang.String getText() {
          java.lang.Object ref = text_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            text_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string text = 1;</code>
         * @return The bytes for text.
         */
        public com.google.protobuf.ByteString
            getTextBytes() {
          java.lang.Object ref = text_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            text_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string text = 1;</code>
         * @param value The text to set.
         * @return This builder for chaining.
         */
        public Builder setText(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          text_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string text = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearText() {
          
          text_ = getDefaultInstance().getText();
          onChanged();
          return this;
        }
        /**
         * <code>string text = 1;</code>
         * @param value The bytes for text to set.
         * @return This builder for chaining.
         */
        public Builder setTextBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          text_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object languageCode_ = "";
        /**
         * <code>string language_code = 2;</code>
         * @return The languageCode.
         */
        public java.lang.String getLanguageCode() {
          java.lang.Object ref = languageCode_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            languageCode_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string language_code = 2;</code>
         * @return The bytes for languageCode.
         */
        public com.google.protobuf.ByteString
            getLanguageCodeBytes() {
          java.lang.Object ref = languageCode_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            languageCode_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string language_code = 2;</code>
         * @param value The languageCode to set.
         * @return This builder for chaining.
         */
        public Builder setLanguageCode(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          languageCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string language_code = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearLanguageCode() {
          
          languageCode_ = getDefaultInstance().getLanguageCode();
          onChanged();
          return this;
        }
        /**
         * <code>string language_code = 2;</code>
         * @param value The bytes for languageCode to set.
         * @return This builder for chaining.
         */
        public Builder setLanguageCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          languageCode_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:QueryInput.text)
      }

      // @@protoc_insertion_point(class_scope:QueryInput.text)
      private static final com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text();
      }

      public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<text>
          PARSER = new com.google.protobuf.AbstractParser<text>() {
        @java.lang.Override
        public text parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new text(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<text> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<text> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int QUERY_INPUT_FIELD_NUMBER = 1;
    private com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text queryInput_;
    /**
     * <code>.QueryInput.text query_input = 1;</code>
     * @return Whether the queryInput field is set.
     */
    public boolean hasQueryInput() {
      return queryInput_ != null;
    }
    /**
     * <code>.QueryInput.text query_input = 1;</code>
     * @return The queryInput.
     */
    public com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text getQueryInput() {
      return queryInput_ == null ? com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.getDefaultInstance() : queryInput_;
    }
    /**
     * <code>.QueryInput.text query_input = 1;</code>
     */
    public com.samdasu.netty.protocol.QueryInputProtos.QueryInput.textOrBuilder getQueryInputOrBuilder() {
      return getQueryInput();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (queryInput_ != null) {
        output.writeMessage(1, getQueryInput());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (queryInput_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getQueryInput());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.samdasu.netty.protocol.QueryInputProtos.QueryInput)) {
        return super.equals(obj);
      }
      com.samdasu.netty.protocol.QueryInputProtos.QueryInput other = (com.samdasu.netty.protocol.QueryInputProtos.QueryInput) obj;

      if (hasQueryInput() != other.hasQueryInput()) return false;
      if (hasQueryInput()) {
        if (!getQueryInput()
            .equals(other.getQueryInput())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasQueryInput()) {
        hash = (37 * hash) + QUERY_INPUT_FIELD_NUMBER;
        hash = (53 * hash) + getQueryInput().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.samdasu.netty.protocol.QueryInputProtos.QueryInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueryInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QueryInput)
        com.samdasu.netty.protocol.QueryInputProtos.QueryInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.samdasu.netty.protocol.QueryInputProtos.internal_static_QueryInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.samdasu.netty.protocol.QueryInputProtos.internal_static_QueryInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.samdasu.netty.protocol.QueryInputProtos.QueryInput.class, com.samdasu.netty.protocol.QueryInputProtos.QueryInput.Builder.class);
      }

      // Construct using com.samdasu.netty.protocol.QueryInputProtos.QueryInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (queryInputBuilder_ == null) {
          queryInput_ = null;
        } else {
          queryInput_ = null;
          queryInputBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.samdasu.netty.protocol.QueryInputProtos.internal_static_QueryInput_descriptor;
      }

      @java.lang.Override
      public com.samdasu.netty.protocol.QueryInputProtos.QueryInput getDefaultInstanceForType() {
        return com.samdasu.netty.protocol.QueryInputProtos.QueryInput.getDefaultInstance();
      }

      @java.lang.Override
      public com.samdasu.netty.protocol.QueryInputProtos.QueryInput build() {
        com.samdasu.netty.protocol.QueryInputProtos.QueryInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.samdasu.netty.protocol.QueryInputProtos.QueryInput buildPartial() {
        com.samdasu.netty.protocol.QueryInputProtos.QueryInput result = new com.samdasu.netty.protocol.QueryInputProtos.QueryInput(this);
        if (queryInputBuilder_ == null) {
          result.queryInput_ = queryInput_;
        } else {
          result.queryInput_ = queryInputBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.samdasu.netty.protocol.QueryInputProtos.QueryInput) {
          return mergeFrom((com.samdasu.netty.protocol.QueryInputProtos.QueryInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.samdasu.netty.protocol.QueryInputProtos.QueryInput other) {
        if (other == com.samdasu.netty.protocol.QueryInputProtos.QueryInput.getDefaultInstance()) return this;
        if (other.hasQueryInput()) {
          mergeQueryInput(other.getQueryInput());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.samdasu.netty.protocol.QueryInputProtos.QueryInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.samdasu.netty.protocol.QueryInputProtos.QueryInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text queryInput_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text, com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.Builder, com.samdasu.netty.protocol.QueryInputProtos.QueryInput.textOrBuilder> queryInputBuilder_;
      /**
       * <code>.QueryInput.text query_input = 1;</code>
       * @return Whether the queryInput field is set.
       */
      public boolean hasQueryInput() {
        return queryInputBuilder_ != null || queryInput_ != null;
      }
      /**
       * <code>.QueryInput.text query_input = 1;</code>
       * @return The queryInput.
       */
      public com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text getQueryInput() {
        if (queryInputBuilder_ == null) {
          return queryInput_ == null ? com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.getDefaultInstance() : queryInput_;
        } else {
          return queryInputBuilder_.getMessage();
        }
      }
      /**
       * <code>.QueryInput.text query_input = 1;</code>
       */
      public Builder setQueryInput(com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text value) {
        if (queryInputBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          queryInput_ = value;
          onChanged();
        } else {
          queryInputBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.QueryInput.text query_input = 1;</code>
       */
      public Builder setQueryInput(
          com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.Builder builderForValue) {
        if (queryInputBuilder_ == null) {
          queryInput_ = builderForValue.build();
          onChanged();
        } else {
          queryInputBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.QueryInput.text query_input = 1;</code>
       */
      public Builder mergeQueryInput(com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text value) {
        if (queryInputBuilder_ == null) {
          if (queryInput_ != null) {
            queryInput_ =
              com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.newBuilder(queryInput_).mergeFrom(value).buildPartial();
          } else {
            queryInput_ = value;
          }
          onChanged();
        } else {
          queryInputBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.QueryInput.text query_input = 1;</code>
       */
      public Builder clearQueryInput() {
        if (queryInputBuilder_ == null) {
          queryInput_ = null;
          onChanged();
        } else {
          queryInput_ = null;
          queryInputBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.QueryInput.text query_input = 1;</code>
       */
      public com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.Builder getQueryInputBuilder() {
        
        onChanged();
        return getQueryInputFieldBuilder().getBuilder();
      }
      /**
       * <code>.QueryInput.text query_input = 1;</code>
       */
      public com.samdasu.netty.protocol.QueryInputProtos.QueryInput.textOrBuilder getQueryInputOrBuilder() {
        if (queryInputBuilder_ != null) {
          return queryInputBuilder_.getMessageOrBuilder();
        } else {
          return queryInput_ == null ?
              com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.getDefaultInstance() : queryInput_;
        }
      }
      /**
       * <code>.QueryInput.text query_input = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text, com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.Builder, com.samdasu.netty.protocol.QueryInputProtos.QueryInput.textOrBuilder> 
          getQueryInputFieldBuilder() {
        if (queryInputBuilder_ == null) {
          queryInputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text, com.samdasu.netty.protocol.QueryInputProtos.QueryInput.text.Builder, com.samdasu.netty.protocol.QueryInputProtos.QueryInput.textOrBuilder>(
                  getQueryInput(),
                  getParentForChildren(),
                  isClean());
          queryInput_ = null;
        }
        return queryInputBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QueryInput)
    }

    // @@protoc_insertion_point(class_scope:QueryInput)
    private static final com.samdasu.netty.protocol.QueryInputProtos.QueryInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.samdasu.netty.protocol.QueryInputProtos.QueryInput();
    }

    public static com.samdasu.netty.protocol.QueryInputProtos.QueryInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryInput>
        PARSER = new com.google.protobuf.AbstractParser<QueryInput>() {
      @java.lang.Override
      public QueryInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.samdasu.netty.protocol.QueryInputProtos.QueryInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryInput_text_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryInput_text_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020queryinput.proto\"`\n\nQueryInput\022%\n\013quer" +
      "y_input\030\001 \001(\0132\020.QueryInput.text\032+\n\004text\022" +
      "\014\n\004text\030\001 \001(\t\022\025\n\rlanguage_code\030\002 \001(\tB.\n\032" +
      "com.samdasu.netty.protocolB\020QueryInputPr" +
      "otosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_QueryInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryInput_descriptor,
        new java.lang.String[] { "QueryInput", });
    internal_static_QueryInput_text_descriptor =
      internal_static_QueryInput_descriptor.getNestedTypes().get(0);
    internal_static_QueryInput_text_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryInput_text_descriptor,
        new java.lang.String[] { "Text", "LanguageCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
